SoSimpleGraphsBundle\Entity\Graph:
    type: entity
    table: null
    repositoryClass: SoSimpleGraphsBundle\Repository\GraphRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
