_index:
    path:     /
    defaults: { _controller: "SoSimpleGraphsBundle:Graph:index" }
    methods:  GET

_show:
    path:     /{id}/show
    defaults: { _controller: "SoSimpleGraphsBundle:Graph:show" }
    methods:  GET

_new:
    path:     /new
    defaults: { _controller: "SoSimpleGraphsBundle:Graph:new" }
    methods:  [GET, POST]

_edit:
    path:     /{id}/edit
    defaults: { _controller: "SoSimpleGraphsBundle:Graph:edit" }
    methods:  [GET, POST]

_delete:
    path:     /{id}/delete
    defaults: { _controller: "SoSimpleGraphsBundle:Graph:delete" }
    methods:  DELETE
